services:
  _defaults:
    autowire: true
    autoconfigure: true

  Adimeo\Notifications\Services\NotificationManager:
    arguments:
      $publisher: '@mercure.hub.default.publisher'
      $entityManager: '@doctrine.orm.entity_manager'
      $normalizer: '@Symfony\Component\Serializer\Normalizer\NormalizerInterface'

  Adimeo\Notifications\EventSubscriber\NotificationSubscriber:

  Adimeo\Notifications\Message\Handler\UserNotificationHandler:
    tags:
      name: messenger.message_handler
      handles: Adimeo\Notifications\Message\Notification\UserNotification
